# After changing this file, check it on http://lint.travis-ci.org/
language: python
sudo: false

python: 3.5
env:
  - TOX_ENV=py35
  - TOX_ENV=py34
  - TOX_ENV=py27

install:
  - python -m pip install -U pip setuptools wheel
  - python -m pip install -U tox

script:
  - python -m tox -e $TOX_ENV -- -sv
